name: Bug report
description: Reporting an issue
labels: ["bug"]
body:
  - type: dropdown
    attributes:
      label: Operating System
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: input
    attributes:
      label: Web Browser
      description: On which web browser do you have a problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue description
      description: A short description of the issue
    validations:
      required: true
