name: Bug Report
description: Suggesting a new wiki to add
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What would you like the wiki to cover?
      description: A short description of the feature you wish the wiki would cover
    validations:
      required: true
